

main: main.c
	gcc -std=c17 src/main.c -IC:\Users\Downtown\OneDrive\Desktop\Projects\NN-Flappy-B-in-C\src\SDL2\include -LC:\Users\Downtown\OneDrive\Desktop\Projects\NN-Flappy-B-in-C\src\SDL2\lib -Wall -lmingw32 -lSDL2main -lSDL2 -o main